int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int lettre);
int _isalpha(int lettre);
int print_sign(int num);
int _abs(int num);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
